### ISSUE TITLE
Remaining setup for Weblate integration

### ISSUE THREAD

**Issue by comradekingu** [scrutin-app/scrutin#8]
https://hosted.weblate.org/projects/scrutin/app/#information says "Proprietary"
whereas
https://github.com/scrutin-app/scrutin/blob/main/LICENSE.md
says AGPLv3
Guessing you want "AGPLv3-or-later" in
https://hosted.weblate.org/settings/scrutin/app
and
https://hosted.weblate.org/settings/scrutin/glossary/

Edit: I can have a look at the rest of the setup if you add "kingu" in https://hosted.weblate.org/access/termux-monet/#users

**Comment by mjal** [comment]
Hello @comradekingu,

Thank you, the Weblate configuration was indeed wrong.
I changed it to AGPLv1-or-later (I don't find AGPLv3-or-later in the list)
You now have access if you want to take a look

**Comment by comradekingu** [comment]
@mjal I found AGPLv3+ and added that.
Seems there is some merge conflict in https://hosted.weblate.org/projects/scrutin/#repository

**Comment by mjal** [comment]
The conflict is resolved, everything should be fine now.

**Comment by comradekingu** [comment]
@mjal I think it only needs #10 then, as a requirement of https://hosted.weblate.org/hosting/
>Mention you use Weblate for translations in the README.
